d/z-push-common.postinst: Don't specify command with full path
This fixes a lintian warning:
  W: z-push-common: command-with-path-in-maintainer-script postinst:93

diff --git a/debian/z-push-common.postinst b/debian/z-push-common.postinst
--- a/debian/z-push-common.postinst
+++ b/debian/z-push-common.postinst
@@ -90,8 +90,8 @@ case "$1" in
 		set_perms www-data www-data 700 /var/log/z-push
 
 		if [ -f /var/lib/z-push/settings -o -f /var/lib/z-push/users ]; then
-			if ! /usr/sbin/z-push-admin -a fixstates >/dev/null 2>&1 ; then
-				echo "Error running command '/usr/sbin/z-push-admin -a fixstates'" >&2
+			if ! z-push-admin -a fixstates >/dev/null 2>&1 ; then
+				echo "Error running command 'z-push-admin -a fixstates'" >&2
 				echo "Please fix the issue and run this command manually." >&2
 			fi
 		fi
